name: Report Bug | 报告BUG
description: "Report bug"
title: "[Bug]: "
labels: []
body:
  - type: dropdown
    id: download
    attributes:
      label: Installation Method | 安装方法与平台
      options:
        - Please choose | 请选择
        - Pip Install (I ignored requirements.txt)
        - Pip Install (I used latest requirements.txt)
        - Anaconda (I ignored requirements.txt)
        - Anaconda (I used latest requirements.txt)
        - Docker（Windows/Mac）
        - Docker（Linux）
        - Docker-Compose（Windows/Mac）
        - Docker-Compose（Linux）
        - Huggingface
        - Others (Please Describe)
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version | 版本
      options:
        - Please choose | 请选择
        - Latest | 最新版
        - Others | 非最新版
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: OS | 操作系统
      options:
        - Please choose | 请选择
        - Windows
        - Mac
        - Linux
        - Docker
    validations:
      required: true
      
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug | 简述
      description: Describe the bug | 简述
    validations:
      required: true
      
  - type: textarea
    id: screenshot
    attributes:
      label: Screen Shot | 有帮助的截图
      description: Screen Shot | 有帮助的截图
    validations:
      required: true
      
  - type: textarea
    id: traceback
    attributes:
      label: Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
      description: Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）






